In [4]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn.linear_model import RidgeCV, LassoCV,ElasticNetCV
import requests
import io

In [16]:
url = "https://gist.githubusercontent.com/keeganhines/59974f1ebef97bbaa44fb19143f90bad/raw/d9bcf657f97201394a59fffd801c44347eb7e28d/Hitters.csv"
stream = requests.get(url).content
df = pd.read_csv(io.StringIO(stream.decode('utf-8')), index_col=0)
df = df.dropna()
df

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  \
-Alan Ashby          315    81      7    24   38     39     14    3449    835   
-Alvin Davis         479   130     18    66   72     76      3    1624    457   
-Andre Dawson        496   141     20    65   78     37     11    5628   1575   
-Andres Galarraga    321    87     10    39   42     30      2     396    101   
-Alfredo Griffin     594   169      4    74   51     35     11    4408   1133   
...                  ...   ...    ...   ...  ...    ...    ...     ...    ...   
-Willie McGee        497   127      7    65   48     37      5    2703    806   
-Willie Randolph     492   136      5    76   50     94     12    5511   1511   
-Wayne Tolleson      475   126      3    61   43     52      6    1700    433   
-Willie Upshaw       573   144      9    85   60     78      8    3198    857   
-Willie Wilson       631   170      9    77   44     31     11    4908   1457   

                   CHmRun  CRuns  CRBI  CWalks League Division  PutOuts  \
-Alan Ashby            69    321   414     375      N        W      632   
-Alvin Davis           63    224   266     263      A        W      880   
-Andre Dawson         225    828   838     354      N        E      200   
-Andres Galarraga      12     48    46      33      N        E      805   
-Alfredo Griffin       19    501   336     194      A        W      282   
...                   ...    ...   ...     ...    ...      ...      ...   
-Willie McGee          32    379   311     138      N        E      325   
-Willie Randolph       39    897   451     875      A        E      313   
-Wayne Tolleson         7    217    93     146      A        W       37   
-Willie Upshaw         97    470   420     332      A        E     1314   
-Willie Wilson         30    775   357     249      A        W      408   

                   Assists  Errors  Salary NewLeague  
-Alan Ashby             43      10   475.0         N  
-Alvin Davis            82      14   480.0         A  
-Andre Dawson           11       3   500.0         N  
-Andres Galarraga       40       4    91.5         N  
-Alfredo Griffin       421      25   750.0         A  
...                    ...     ...     ...       ...  
-Willie McGee            9       3   700.0         N  
-Willie Randolph       381      20   875.0         A  
-Wayne Tolleson        113       7   385.0         A  
-Willie Upshaw         131      12   960.0         A  
-Willie Wilson           4       3  1000.0         A  

[263 rows x 20 columns]

In [17]:
dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])

y = df["Salary"]

X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')

X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.25, 
                                                    random_state=42)

In [18]:
enet_model = ElasticNet().fit(X_train, y_train)
enet_model.coef_

/Users/s02435/ghq/github.com/nnao45/jaist-my-jupyter/.venv/lib/python3.9/site-packages/sklearn/linear_model/_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.488e+06, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(


array([ -1.86256172,   8.70489065,   5.10426375,  -2.89875799,
        -1.28642985,   5.24343682,   6.04480276,  -0.14701495,
        -0.21566628,  -0.7897201 ,   1.80813117,   0.80914508,
        -0.61262382,   0.26816203,   0.27172387,  -0.36530729,
        19.2186222 , -31.16586592,   8.98369938])

In [19]:
enet_model.intercept_


-6.465955602112331

In [20]:
enet_model.predict(X_train)[:10]


array([325.74706292, 776.06632333, 522.86508419, 107.64091955,
       449.03139566, 997.76095723,  99.78828622, 311.33763086,
       418.50335021, 879.9502608 ])

In [21]:
enet_model.predict(X_test)[:10]


array([ 577.79111731,  617.33202224, 1031.39113156,  364.95861575,
        489.51894393,  300.74185842,  604.522666  ,  465.34678732,
        901.44473965,  703.20357123])

In [22]:
y_pred = enet_model.predict(X_test)

np.sqrt(mean_squared_error(y_test,y_pred))

357.1676548181246

In [23]:
r2_score(y_test,y_pred)


0.41070222469326867

In [24]:
enet_cv_model = ElasticNetCV(cv = 10).fit(X_train,y_train)

# If we don't give the lambdas, what's the alpha?

enet_cv_model.alpha_

5230.7647364798695

In [25]:
enet_cv_model.intercept_


-38.5194055839429

In [26]:
enet_cv_model.coef_


array([ 0.62845434,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.09788752,  0.        ,
        0.27265769,  0.19270075,  0.00758665,  0.3106529 ,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        ])

In [27]:
# Let's create the final model according to optimum alpha.

enet_tuned = ElasticNet(alpha = enet_cv_model.alpha_).fit(X_train,y_train)

# Let's now calculate the error for the test set using this final model.

y_pred = enet_tuned.predict(X_test)

np.sqrt(mean_squared_error(y_test,y_pred))

394.15280563218795